import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
from myclim import initialise_aod_responses
#
aod_strat_sh, aod_strat_nh, nbyr_irf = initialise_aod_responses()
#
plt.plot(aod_strat_sh['eq'],color='red',label='Eq')
plt.plot(aod_strat_sh['15N'],color='blue',linestyle='dashed',label='15N')
plt.plot(aod_strat_sh['15S'],color='blue',label='15S')
plt.plot(aod_strat_sh['30N'],color='green',linestyle='dashed',label='30N')
plt.plot(aod_strat_sh['30S'],color='green',label='30S')
plt.plot(aod_strat_sh['60N'],color='purple',linestyle='dashed',label='60N')
plt.plot(aod_strat_sh['60S'],color='purple',label='60S')
plt.legend()
plt.xlim(-0.5,6.5)
plt.title('SH AOD for pulse emissions')
plt.savefig('SH_AOD.png')
plt.show()
#
plt.plot(aod_strat_nh['eq'],color='red',label='Eq')
plt.plot(aod_strat_nh['15N'],color='blue',linestyle='dashed',label='15°N')
plt.plot(aod_strat_nh['15S'],color='blue',label='15°S')
plt.plot(aod_strat_nh['30N'],color='green',linestyle='dashed',label='30°N')
plt.plot(aod_strat_nh['30S'],color='green',label='30°S')
plt.plot(aod_strat_nh['60N'],color='purple',linestyle='dashed',label='60°N')
plt.plot(aod_strat_nh['60S'],color='purple',label='60°S')
plt.legend()
plt.xlim(-0.5,6.5)
plt.title('NH AOD for pulse emissions')
plt.savefig('NH_AOD.png')
plt.show()
#
plt.plot((aod_strat_nh['eq']+aod_strat_sh['eq'])/2.,color='red',label='Eq')
plt.plot((aod_strat_nh['15N']+aod_strat_sh['15N'])/2.,color='blue',linestyle='solid',label='15°N')
plt.plot((aod_strat_nh['30N']+aod_strat_sh['30N'])/2.,color='green',linestyle='solid',label='30°N')
plt.plot((aod_strat_nh['60N']+aod_strat_sh['60N'])/2.,color='purple',linestyle='solid',label='60°N')
plt.plot((aod_strat_nh['15S']+aod_strat_sh['15S'])/2.,color='blue',linestyle='dashed',label='15°S')
plt.plot((aod_strat_nh['30S']+aod_strat_sh['30S'])/2.,color='green',linestyle='dashed',label='30°S')
plt.plot((aod_strat_nh['60S']+aod_strat_sh['60S'])/2.,color='purple',linestyle='dashed',label='60°S')
plt.legend()
plt.xlim(-0.5,6.5)
plt.title('Global AOD for pulse emissions')
plt.savefig('global_AOD.png')
plt.show()
#
plt.plot(aod_strat_nh['15N'],color='red',label='NH 15N')
plt.plot(aod_strat_sh['15S'],color='red',label='SH 15S',linestyle='dashed')
plt.plot(aod_strat_nh['15S'],color='blue',label='NH 15S')
plt.plot(aod_strat_sh['15N'],color='blue',label='SH 15N',linestyle='dashed')
plt.plot((aod_strat_nh['15N']+aod_strat_sh['15N'])/2.,color='orange',label='Global 15°N')
plt.plot((aod_strat_nh['15S']+aod_strat_sh['15S'])/2.,color='purple',label='Global 15°S')
plt.legend()
plt.xlim(-0.5,6.5)
plt.title('AOD for pulse emissions at 15°N / 15°S')
plt.savefig('AOD_emitted_at_15.png')
plt.show()
